[package]
name = "pallet-evm-erc721"
version = "0.0.1"
edition = "2021"

[dependencies]
parity-scale-codec = { workspace = true, features = [
	"derive",
] }
scale-info = { workspace = true, features = [
	"derive",
] }

# Frontier
fp-evm = { workspace = true }
pallet-evm = { workspace = true }

# Substrate
frame-support = { workspace = true }
sp-arithmetic = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# Local pallet
pallet-living-assets-ownership = { workspace = true }

# Utils
precompile-utils = { workspace = true }
precompile-utils-macro = { workspace = true }

num_enum = { workspace = true }

[dev-dependencies]
evm = { workspace = true }
hex = { workspace = true }
precompile-utils = { workspace = true, features = ["testing"]}

[features]
default = ["std"]
std = [
	# Frontier
	"fp-evm/std",
	"pallet-evm/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"pallet-living-assets-ownership/std",
	"num_enum/std",
	"frame-support/std",
	"sp-arithmetic/std",
	"precompile-utils/std",
	"parity-scale-codec/std",
	"scale-info/std",
]
