[package]
name = "laos-runtime-api-staking"
authors = { workspace = true }
edition = "2021"
version = "0.1.0"
description = "Runtime APIs for dealing with parachain staking."

[dependencies]
# External dependencies
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }

# Substrate dependencies
sp-api = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = [
  "parity-scale-codec/std",
  "sp-api/std",
  "sp-runtime/std",
  "scale-info/std",
]
