[settings]
provider = "native"

[relaychain]
default_command = "{{ZOMBIENET_RELAYCHAIN_COMMAND}}"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "relay1"
  ws_port = 9944
  validator = true

  [[relaychain.nodes]]
  name = "relay2"
  validator = true

  [[relaychain.nodes]]
  name = "relay3"
  validator = true

[[parachains]]
id = 2900
cumulus_based = true
chain = "local"
force_decorator = "generic-evm"

  [[parachains.collators]]
  name = "laos"
  ws_port = 9999
  command = "{{ZOMBIENET_LAOS_COMMAND}}"
  validator = true

[[parachains]]
id = 2000
cumulus_based = true
chain = "asset-hub-rococo-local"

  [[parachains.collators]]
  name = "asset-hub"
  validator = true
  ws_port = 9950
  command = "{{ZOMBIENET_ASSETHUB_COMMAND}}"
  args = ["--log=xcm=trace,pallet-assets=trace"]

# [[hrmp_channels]]
# sender = 2900
# recipient = 2000
# max_capacity = 8
# max_message_size = 1048576