[package]
name = "pallet-evm-laos-evolution"
version = "2.0.0-dev"
description = "Living assets evolution precompile"
repository = "https://github.com/freeverseio/pallet-livingassets-ownership"
edition = "2021"

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }

# Frontier
fp-evm = { workspace = true, features = ["serde"] }
pallet-evm = { workspace = true }

# Substrate
frame-support = { workspace = true }
sp-arithmetic = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# Local pallet
pallet-laos-evolution = { workspace = true }

# Local precompile utils
laos-precompile-utils-macro = { workspace = true }
laos-precompile-utils = { workspace = true }

# Frontier precompile utils
precompile-utils = { workspace = true }

num_enum = { workspace = true }

[dev-dependencies]
evm = { workspace = true }
hex = { workspace = true }
laos-precompile-utils = { workspace = true, features = ["testing"]}
precompile-utils = { workspace = true, features = ["testing"]}
parity-scale-codec = { workspace = true, features = ["derive"] }
frame-system = { workspace = true }
pallet-balances = { workspace = true, features = ["std", "insecure_zero_ed"] }
pallet-timestamp = { workspace = true }
sp-io = { workspace = true }

[features]
default = ["std"]
std = [
	# Frontier
	"fp-evm/std",
	"pallet-evm/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"pallet-laos-evolution/std",
	"num_enum/std",
	"frame-support/std",
	"sp-arithmetic/std",
	"laos-precompile-utils/std",
	"parity-scale-codec/std",
	"scale-info/std",
]
