[package]
name = "pallet-evm-evolution-collection"
version = "2.0.0-dev"
description = "Collection evolver and minter precompile"
repository = "https://github.com/freeverseio/laos"
edition = "2021"

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }

# Frontier
fp-evm = { workspace = true, features = ["serde"] }
pallet-evm = { workspace = true }

# Substrate
frame-support = { workspace = true }
sp-arithmetic = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# Local pallet
pallet-laos-evolution = { workspace = true }

# Utils
laos-precompile-utils-macro = { workspace = true }
laos-precompile-utils = { workspace = true }

num_enum = { workspace = true }

[dev-dependencies]
evm = { workspace = true }
hex = { workspace = true }
laos-precompile-utils = { workspace = true, features = ["testing"]}

[features]
default = ["std"]
std = [
	# Frontier
	"fp-evm/std",
	"pallet-evm/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"pallet-laos-evolution/std",
	"num_enum/std",
	"frame-support/std",
	"sp-arithmetic/std",
	"laos-precompile-utils/std",
	"parity-scale-codec/std",
	"scale-info/std",
]
