name: 'Setup'
description: 'Common setup steps'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Install linux dependencies
      run: sudo apt-get install -y clang libssl-dev llvm libudev-dev protobuf-compiler
      shell: bash
    - name: Install Rust
      run: |
        rustup update stable --no-self-update
        rustup target add wasm32-unknown-unknown
      shell: bash
