name: ChatGPT

on:
  pull_request:
    types: 
      - opened
      - synchronize
  workflow_dispatch:
  
    
jobs:
  review:
    if: ${{ contains( github.event.label.name, 'AutoReview') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check if Draft
        id: check
        run: echo "is_draft=${{ github.event.pull_request.draft }}" >> $GITHUB_OUTPUT
      
      - name: Run if Draft
        if: steps.check.outputs.is_draft == 'true'
        uses: gvasilei/AutoReviewer@0.4
        env:
          NODE_OPTIONS: '--experimental-fetch'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          model_name: gpt-4
