name: ChatGPT

on:
  pull_request:
  issue_comment:
  
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Conditions
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENTER="${{ github.event.comment.user.login }}"
          echo "COMMENTER=$COMMENTER" >> $GITHUB_ENV
          echo "Commenter is $COMMENTER"
      - name: Run if Commenter
        if: env.COMMENTER != ''
        uses: Codium-ai/pr-agent@v0.8
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_DESCRIPTION.PUBLISH_LABELS: false
          PR_DESCRIPTION.PUBLISH_DESCRIPTION_AS_COMMENT: true
