name: ChatGPT

on:
  pull_request:
    types: 
      - opened
      - synchronize
  workflow_dispatch:
  
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check if Draft
        id: check
        run: echo "is_draft=${{ github.event.pull_request.draft }}" >> $GITHUB_OUTPUT
      
      - name: Run if Draft
        if: steps.check.outputs.is_draft == 'true'
        uses: adshao/chatgpt-code-review-action@v0.2.5
        with:
          OPENAI_TOKEN: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FULL_REVIEW_COMMENT: 'chatgpt'
          REVIEW_COMMENT_PREFIX: 'chatgpt:'
