name: ChatGPT

on:
  pull_request:
    types:
      - opened
      - synchronize
  issue_comment:
    types:
      - created
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Conditions
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Determine if this is a PR or an issue comment event
          IS_PR_EVENT=${{ github.event_name == 'pull_request' }}
          IS_COMMENT_EVENT=${{ github.event_name == 'issue_comment' }}
          
          # Fetch the PR creator
          PRCREATOR=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }} | jq -r .user.login)
          
          # Check if the PR creator is in the group
          IS_IN_GROUP=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/orgs/freeverseio/teams/ziggy/members/$PRCREATOR)
          if [ "$IS_IN_GROUP" != "null" ]; then
            echo "Commenter is in the group."
            echo "is_in_group=true" >> $GITHUB_ENV
          else
            echo "Commenter is not in the group."
            echo "is_in_group=false" >> $GITHUB_ENV
          fi
          
          # Check if the comment contains [autoreview] (if this is a comment event)
          if [[ "$IS_COMMENT_EVENT" == "true" ]]; then
            COMMENT_BODY="${{ github.event.comment.body }}"
            echo "is_autoreview=$(if [[ "$COMMENT_BODY" == *"[autoreview]"* ]]; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_ENV
          else
            echo "is_autoreview=false" >> $GITHUB_ENV
          fi
          
          echo "is_draft=${{ github.event.pull_request.draft }}" >> $GITHUB_ENV

      - name: Run if Draft, Correct User, and AutoReview
        if: env.is_draft == 'true' && env.is_in_group == 'true' && env.is_autoreview == 'true'
        uses: gvasilei/AutoReviewer@0.4
        env:
          NODE_OPTIONS: '--experimental-fetch'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          model_name: gpt-4
