name: ChatGPT

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Conditions
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.user.login }})
          if [ $? -ne 0 ]; then
            echo "Failed to fetch issue details"
            exit 1
          fi
          PRCREATOR=$(echo "$response" | jq -r .user.login)
          IS_IN_GROUP=$(echo "$response" | jq -r '.teams[] | select(.name == "ziggy") | .members[] | select(.login == $PRCREATOR)')
          if [ -n "$IS_IN_GROUP" ]; then
            echo "Commenter is in the group."
            echo "is_in_group=true" >> $GITHUB_ENV
          else
            echo "Commenter is not in the group."
            echo "is_in_group=false" >> $GITHUB_ENV
          fi
          echo "is_autoreview=$(if [[ "${{ github.event.pull_request.title }}" == *"[autoreview]"* ]]; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_ENV
          echo "is_draft=${{ github.event.pull_request.draft }}" >> $GITHUB_ENV

      - name: Run if Draft, Correct User, and AutoReview
        if: steps.check.outputs.is_draft == 'true' && steps.check.outputs.is_in_group == 'true' && steps.check.outputs.is_autoreview == 'true'
        uses: gvasilei/AutoReviewer@0.4
        env:
          NODE_OPTIONS: '--experimental-fetch'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          model_name: gpt-4
