name: ChatGPT

on:
  pull_request:
    types: 
      - opened
      - synchronize
  workflow_dispatch:
  
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check if Draft
        id: check
        run: echo "::set-output name=is_draft::${{ github.event.pull_request.draft }}"
      
      - name: Run if Draft
        if: steps.check.outputs.is_draft == 'true'
        uses: magnificode-ltd/chatgpt-code-reviewer@v0.0.8
        with:
          model: gpt-4
        # max_tokens: 4096
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
