name: Try Runtime

# Controls when the action will run.
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

# Set an environment variable (that can be overriden) for the Docker Repo
env:
  DOCKER_REPO: freeverseio/laos-ownership-node

jobs:
  laos-owership:
    runs-on: 
      group: laos
      labels: ubuntu-16-cores
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/cache
        with:
          cache-key: try_runtime
      - name: Build
        run: |
          cargo build --release --package laos-ownership --features=try-runtime
      - name: Try Runtime
        run: |
          RUST_LOG=try-runtime ./target/release/laos try-runtime --runtime ./target/release/wbuild/laos-runtime/laos_runtime.wasm on-runtime-upgrade --checks=pre-and-post live --uri ws://143.198.251.52:9944